name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - pip
  - ruamel.yaml
  - numba
  - pip:
      - git+https://github.com/SpikeInterface/spikeinterface.git
      - git+https://github.com/NeuralEnsemble/python-neo.git