name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - pip
  - cudatoolkit=11.3  # Use the CUDA version compatible with your GPU drivers
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - git+https://github.com/SpikeInterface/spikeinterface.git