name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom
  - appdirs
  - blas
  - blas-devel
  - blosc
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - cryptography
  - cudatoolkit=11.3
  - cupy
  - cutensor
  - cython
  - cytoolz
  - dask-core
  - dav1d
  - fastrlock
  - ffmpeg
  - fftw
  - freetype
  - fsspec
  - giflib
  - gmp
  - gnutls
  - icu
  - idna
  - imagecodecs
  - imageio
  - jpeg
  - jxrlib
  - keyutils
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libhwloc
  - libiconv
  - liblapack
  - liblapacke
  - libnghttp2
  - libnsl
  - libpng
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - libzopfli
  - llvm-openmp
  - locket
  - lz4-c
  - mkl
  - mkl-devel
  - mkl-include
  - nccl
  - ncurses
  - nettle
  - networkx
  - openh264
  - openjpeg
  - openssl
  - packaging
  - partd
  - pillow
  - pip
  - pooch
  - pthread-stubs
  - pycparser
  - pydantic
  - pyfftw=0.12.0
  - pyopenssl
  - pysocks
  - python=3.8
  - python_abi
  - python-graphviz
  - pytorch
  - pytorch-mutex
  - pyqt
  - pyqt5-sip
  - pyqtgraph
  - pyqtwebengine
  - pywavelets
  - pyyaml
  - readline
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scikit-image
  - scipy
  - setuptools
  - snappy
  - tbb
  - tifffile
  - tk
  - toolz
  - torchvision
  - typing-extensions
  - typing_extensions
  - urllib3
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zfp
  - zlib
  - zlib-ng
  - zstd
  - pip:
      - aiofiles
      - aiosqlite
      - anyio
      - arrow
      - attrs
      - babel
      - beautifulsoup4
      - boto3
      - botocore
      - colorcet
      - colorlog
      - contourpy
      - cycler
      - easyqc
      - exceptiongroup
      - fastjsonschema
      - flake8
      - fonttools
      - fqdn
      - ghp-import
      - globus-sdk
      - h5py
      - git+https://github.com/int-brain-lab/ibllib.git
      - git+https://github.com/int-brain-lab/iblutil.git
      - git+https://github.com/int-brain-lab/ibl-neuropixel.git
      - importlib-metadata
      - importlib-resources
      - iniconfig
      - isoduration
      - jinja2
      - jmespath
      - joblib
      - json5
      - jsonpointer
      - jsonschema
      - jupyter-client
      - jupyter-core
      - jupyter-events
      - jupyter-server
      - jupyter-server-fileid
      - jupyter-server-terminals
      - jupyter-server-ydoc
      - jupyter-ydoc
      - jupyterlab
      - jupyterlab-server
      - kiwisolver
      - labcams
      - llvmlite
      - markdown
      - matplotlib
      - mccabe
      - mergedeep
      - mistune
      - mkdocs
      - mtscomp
      - natsort
      - nbclassic
      - nbconvert
      - nbformat
      - notebook-shim
      - nptdms
      - nptyping
      - numba
      - numpy
      - one-api
      - opencv-python
      - opencv-python-headless
      - pandas
      - param
      - parmap
      - git+https://github.com/cortex-lab/phy.git
      - git+https://github.com/cortex-lab/phylib.git
      - pims
      - pkgutil-resolve-name
      - platformdirs
      - pluggy
      - pyarrow
      - pycodestyle
      - pyct
      - pyflakes
      - pyjwt
      - pynrrd
      - pyopengl
      - pyrsistent
      - pyserial
      - pytest
      - python-dateutil
      - python-json-logger
      - pytz
      - pyyaml-env-tag
      - pyzmq
      - rfc3339-validator
      - rfc3986-validator
      - s3transfer
      - scikit-learn
      - scikit-video
      - seaborn
      - send2trash
      - six
      - slicerator
      - slidingrp
      - sniffio
      - soupsieve
      - threadpoolctl
      - tinycss2
      - tomli
      - tornado
      - tqdm
      - traitlets
      - uri-template
      - viewephys
      - watchdog
      - webcolors
      - websocket-client
      - wfield
      - y-py
      - ypy-websocket
      - zipp
